# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "PlayTTD::Web"

# Data directory
data: "/var/www/data/"

# Portal folder
folder: "play-ttd/"

# Google analytics
analytics: "UA-32891320-1"

# Title
title: "Transport Tycoon Deluxe Online"

# Description
description: "PlayTTD is an open source browser game based upon Transport Tycoon Deluxe."

# Keywords
keywords: "PlayTTD,play ttd,TTD,Transport Tycoon Deluxe,game,browser,online,play"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

# template: "simple"

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
